# Generated by Django 3.2.18 on 2023-03-02 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pessoa_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_cartao',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipo_cartao')),
            ],
            options={
                'db_table': 'cartao',
            },
        ),
    ]
